// Tree-shaken Font Awesome Free (same pattern as airank): only the icons registered here are bundled, and existing
// <i class="fa-solid fa-x"> markup keeps working through dom.watch. autoReplaceSvg 'nest' keeps Vue's <i> node in
// place. Adding an icon? Use it in a template AND register it here, or it renders as nothing.
import { config, library, dom } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import {
    faBars,
    faChartLine,
    faChartColumn,
    faLayerGroup,
    faClockRotateLeft,
    faSliders,
    faBrain,
    faMicrochip,
    faCircleNodes,
    faWaveSquare,
    faArrowUpRightFromSquare,
    faArrowRight,
    faPause,
    faPlay,
    faMagnifyingGlass,
    faXmark,
    faTerminal,
    faGlobe,
    faTableCellsLarge,
    faCrosshairs,
    faCircleCheck,
    faChevronRight,
    faArrowTrendDown,
    faArrowTrendUp,
    faBolt,
    faChartDiagram,
    faFireFlameCurved,
    faFlagCheckered,
    faPlug,
    faSatelliteDish,
    faServer,
    faShieldHalved,
    faChessKnight,
    faTriangleExclamation,
    faTrophy,
    faVolumeHigh,
    faVolumeXmark,
} from "@fortawesome/free-solid-svg-icons";

config.autoReplaceSvg = "nest";
library.add(
    faBars,
    faChartLine,
    faChartColumn,
    faLayerGroup,
    faClockRotateLeft,
    faSliders,
);
library.add(
    faBrain,
    faMicrochip,
    faCircleNodes,
    faWaveSquare,
    faArrowUpRightFromSquare,
    faArrowRight,
    faPause,
    faPlay,
    faMagnifyingGlass,
    faXmark,
    faTerminal,
    faGlobe,
    faTableCellsLarge,
    faCrosshairs,
    faCircleCheck,
    faChevronRight,
);
config.observeMutations = true;
library.add(
    faArrowTrendDown,
    faArrowTrendUp,
    faBolt,
    faChartDiagram,
    faFireFlameCurved,
    faFlagCheckered,
    faPlug,
    faSatelliteDish,
    faServer,
    faShieldHalved,
    faChessKnight,
    faTriangleExclamation,
    faTrophy,
    faVolumeHigh,
    faVolumeXmark,
);
dom.watch();
