import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import { ref, reactive, computed, watch, nextTick, effectScope } from 'vue';
import { parse, compileScript } from '@vue/compiler-sfc';
import { readQuote, observeQuote } from '../../../resources/js/components/chart/marketLens.js';
import { deskHeaders } from '../../../resources/js/api.js';

const sourceFile = new URL('../../../resources/js/components/chart/ChartMarketDeck.vue', import.meta.url);
const { descriptor } = parse(await fs.readFile(sourceFile, 'utf8'));
const compiled = compileScript(descriptor, { id: 'quote-lifecycle' });
let source = descriptor.scriptSetup.content;
for (const node of compiled.scriptSetupAst.filter(n => n.type === 'ImportDeclaration').reverse()) source = source.slice(0, node.start) + source.slice(node.end);
const listeners = new Set(), requests = [], events = [], mounted = [], unmounted = [];
let poll, timerCleared = false;
const document = { hidden: false, addEventListener(_name, fn) { listeners.add(fn); }, removeEventListener(_name, fn) { listeners.delete(fn); } };
const fetch = (url, options) => new Promise((resolve, reject) => requests.push({ url, signal: options.signal, resolve: data => resolve({ ok: true, json: async () => data }), reject }));
const props = reactive({ symbol: 'BTC-USD', products: [], active: true });
const create = new Function('computed','onMounted','onUnmounted','ref','watch','defineProps','defineEmits','readQuote','observeQuote','deskHeaders','fetch','document','setInterval','clearInterval', `${source}\nreturn {quote,points,error,refresh,status};`);
const scope = effectScope();
const state = scope.run(() => create(computed, fn => mounted.push(fn), fn => unmounted.push(fn), ref, watch, () => props, () => (...args) => events.push(args), readQuote, observeQuote, deskHeaders, fetch, document, fn => { poll = fn; return 1; }, () => { timerCleared = true; }));
const settle = async () => { for (let i = 0; i < 6; i++) await Promise.resolve(); await nextTick(); };
const quote = (symbol, price, ts = Math.floor(Date.now() / 1000)) => ({ product_id: symbol, price, ts, source: 'feed' });
mounted[0](); poll(); poll(); assert.equal(requests.length, 1, 'only one request is in flight');
props.symbol = 'ETH-USD'; await nextTick(); assert.equal(requests[0].signal.aborted, true); assert.equal(requests.length, 2);
requests[1].resolve(quote('ETH-USD', 2000)); await settle();
requests[0].resolve(quote('BTC-USD', 80000)); await settle(); assert.equal(state.quote.value.symbol, 'ETH-USD');
assert.equal(state.points.value.length, 1);
poll(); requests[2].resolve(quote('ETH-USD', 500, 1)); await settle(); assert.equal(state.quote.value.price, 2000);
poll(); requests[3].reject(Error('network')); await settle(); assert.equal(state.status.value, 'Quote unavailable'); assert.deepEqual(events.at(-1), ['quote', null]);
document.hidden = true; for (const fn of listeners) fn(); poll(); assert.equal(requests.length, 4);
props.symbol = 'SOL-USD'; await nextTick(); assert.equal(state.quote.value, null); assert.equal(state.points.value.length, 0);
document.hidden = false; for (const fn of listeners) fn(); assert.equal(requests.length, 5); assert.match(requests[4].url, /SOL-USD/);
requests[4].resolve(quote('SOL-USD', 100, 1)); await settle(); assert.equal(state.status.value, 'Stored snapshot');
poll(); unmounted[0](); scope.stop(); assert.equal(requests[5].signal.aborted, true);
requests[5].resolve(quote('SOL-USD', 999)); await settle(); assert.equal(state.quote.value.price, 100);
assert.equal(timerCleared, true); assert.equal(listeners.size, 0);
console.log('PASS: quote poll overlap, symbol cancellation, out-of-order rejection, failure status, hidden-tab pause, visibility refresh and unmount cleanup');
