server {
    listen 80;
    listen [::]:80;
    server_name shoemoneyx.com www.shoemoneyx.com;
    location /.well-known/acme-challenge/ { root /var/www/html; }
    location / { return 301 https://shoemoneyx.com$request_uri; }
}
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name www.shoemoneyx.com;
    ssl_certificate /etc/letsencrypt/live/shoemoneyx.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/shoemoneyx.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    return 301 https://shoemoneyx.com$request_uri;
}
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name shoemoneyx.com;
    ssl_certificate /etc/letsencrypt/live/shoemoneyx.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/shoemoneyx.com/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    include /etc/nginx/snippets/shoemoneyx-app.conf;
}
