export const brandTreatments = {
    pulse: "Signal fins",
    neural: "Electric branches",
    terminal: "Scanning brackets",
    orbit: "Satellite rings",
    prism: "Folded glass",
    supernova: "Solar shards",
    neon: "Hologram portals",
    reactor: "Turbine teeth",
    liquid: "Fluid ripples",
    citadel: "Architectural crest",
    redline: "Velocity chevrons",
    synapse: "Axon web",
    spectrum: "Chromatic prisms",
    horizon: "Lensing arcs",
    overdrive: "Circuit matrix",
    "pulse-blue": "Signature shield shockwaves",
    "horizon-blue": "Blue lensing arcs",
    "supernova-blue": "Azure plasma shards",
};
