export const explosionDesigns = [
    {
        id: "supernova",
        number: "06",
        name: "Supernova",
        headline: "EVERY SIGNAL. ALL AT ONCE.",
        kicker: "The intelligence singularity",
        scene: "starburst",
        accent: "#ff773b",
        second: "#ffdfa6",
        light: false,
        sceneTitle: "SIGNAL ACCELERATOR",
        description: "Every market feeds one intelligence.",
        layout: "orbital",
    },
    {
        id: "neon",
        number: "07",
        name: "Neon",
        headline: "THE MARKET NEVER SLEEPS.",
        kicker: "Night shift / always on",
        scene: "grid",
        accent: "#f454df",
        second: "#32e7eb",
        light: false,
        sceneTitle: "NEURAL FREQUENCY",
        description: "Signals in. Decisions out.",
        layout: "wall",
    },
    {
        id: "reactor",
        number: "08",
        name: "Reactor",
        headline: "INTELLIGENCE UNDER LOAD.",
        kicker: "Autonomous trading facility",
        scene: "reactor",
        accent: "#ffd445",
        second: "#ff692f",
        light: false,
        sceneTitle: "CORE ACTIVITY",
        description: "A machine built to read the market.",
        layout: "split",
    },
    {
        id: "liquid",
        number: "09",
        name: "Liquid",
        headline: "FOLLOW THE FLOW.",
        kicker: "A living view of your capital",
        scene: "waves",
        accent: "#53eed3",
        second: "#418eff",
        light: false,
        sceneTitle: "LIQUIDITY FIELD",
        description: "One fluid system. Every moving market.",
        layout: "flow",
    },
    {
        id: "citadel",
        number: "10",
        name: "Citadel",
        headline: "YOUR EDGE. AT SCALE.",
        kicker: "The market has a new skyline",
        scene: "city",
        accent: "#b7fa64",
        second: "#71b4ff",
        light: false,
        sceneTitle: "CAPITAL ARCHITECTURE",
        description: "Market towers sized by deployed capital.",
        layout: "split",
    },
    {
        id: "redline",
        number: "11",
        name: "Redline",
        headline: "FULL MARKET. FULL THROTTLE.",
        kicker: "Every position. Every split second.",
        scene: "tunnel",
        accent: "#ff4545",
        second: "#fff4d9",
        light: false,
        sceneTitle: "EXECUTION VELOCITY",
        description: "Intelligence at the speed of the market.",
        layout: "race",
    },
    {
        id: "synapse",
        number: "12",
        name: "Synapse",
        headline: "THINK IN EVERY DIRECTION.",
        kicker: "The connected trading mind",
        scene: "neural",
        accent: "#b596ff",
        second: "#d4ff69",
        light: false,
        sceneTitle: "COGNITIVE NETWORK",
        description: "Every pair, connected to the same brain.",
        layout: "orbital",
    },
    {
        id: "spectrum",
        number: "13",
        name: "Spectrum",
        headline: "MAKE THE MARKET VISIBLE.",
        kicker: "All the movement. Nothing hidden.",
        scene: "spectrum",
        accent: "#77b6ff",
        second: "#ff76c9",
        light: false,
        sceneTitle: "MARKET FREQUENCIES",
        description: "A full spectrum of trading intelligence.",
        layout: "mosaic",
    },
    {
        id: "horizon",
        number: "14",
        name: "Event Horizon",
        headline: "ALL SIGNALS CONVERGE.",
        kicker: "Enter the center of the market",
        scene: "blackhole",
        accent: "#f5dcc0",
        second: "#ff8f4b",
        light: false,
        sceneTitle: "THE POINT OF CONVERGENCE",
        description: "Thousands of moving parts. One living system.",
        layout: "orbital",
    },
    {
        id: "overdrive",
        number: "15",
        name: "Overdrive",
        headline: "ABSOLUTE MARKET AWARENESS.",
        kicker: "The entire operation. In overdrive.",
        scene: "matrix",
        accent: "#59a5ff",
        second: "#68f5c8",
        light: false,
        sceneTitle: "GLOBAL SIGNAL FABRIC",
        description: "The complete trading firehose, made visible.",
        layout: "wall",
    },
    {
        id: "horizon-blue",
        family: "horizon",
        colorway: "blue",
        number: "17",
        name: "Event Horizon Blue",
        headline: "ALL SIGNALS CONVERGE.",
        kicker: "The blue edition / enter the singularity",
        scene: "blackhole",
        accent: "#55b5ff",
        second: "#1782ff",
        light: false,
        sceneTitle: "THE POINT OF CONVERGENCE",
        description: "Thousands of moving parts. One living system.",
        layout: "orbital",
    },
    {
        id: "supernova-blue",
        family: "supernova",
        colorway: "blue",
        number: "18",
        name: "Supernova Blue",
        headline: "EVERY SIGNAL. ALL AT ONCE.",
        kicker: "The blue edition / intelligence in motion",
        scene: "starburst",
        accent: "#55b5ff",
        second: "#1782ff",
        light: false,
        sceneTitle: "SIGNAL ACCELERATOR",
        description: "Every market feeds one intelligence.",
        layout: "orbital",
    },
];
