export const picasoEnhancements = {
    "horizon-blue": [
        "Electric blue photon arcs",
        "Cyan accretion streams",
        "Royal blue lensing rings",
        "Blue P&L convergence well",
        "ShoeMoney gravitational crest",
    ],
    "supernova-blue": [
        "Azure plasma prominences",
        "Blue P&L ejecta bursts",
        "Cyan magnetic corona",
        "Electric blue shockwave dial",
        "ShoeMoney plasma insignia",
    ],
    "pulse-blue": [
        "Integrated ShoeMoney logo",
        "Azure signal field",
        "Blue market pressure equalizer",
        "Cyan P&L ignition",
        "Branded AI relay",
    ],
    pulse: [
        "Signal shockwaves",
        "Market pressure equalizer",
        "P&L ignition sweep",
        "Magnetic signal cards",
        "Agent transmission chase",
    ],
    neural: [
        "Dendrite constellation",
        "Synaptic route console",
        "P&L synapse bloom",
        "Focus-linked neural wires",
        "Agent firing cascade",
    ],
    terminal: [
        "Packet rain",
        "Live packet buffer",
        "P&L raster decode",
        "Row targeting scanner",
        "Pipeline process tracer",
    ],
    orbit: [
        "Comet field",
        "Capital satellite belt",
        "P&L gravitational echo",
        "Focused orbital uplinks",
        "Agent orbital telemetry",
    ],
    prism: [
        "Refractive ribbons",
        "Capital color mosaic",
        "P&L chromatic shutter",
        "Pointer-lit glass cards",
        "Agent color relay",
    ],
    supernova: [
        "Solar prominences",
        "P&L ejecta bursts",
        "Magnetic corona lens",
        "P&L shockwave dial",
        "Plasma targeting lens",
    ],
    neon: [
        "Holographic scan walls",
        "Quote packet fountains",
        "Hexagonal targeting lens",
        "Holographic P&L scanner",
        "Chromatic market projection",
    ],
    reactor: [
        "Segmented turbine vanes",
        "P&L pressure rings",
        "Geared iris lock",
        "Segmented profit turbine",
        "Armored instrument targeting",
    ],
    liquid: [
        "Iridescent wave sheets",
        "Quote splash wakes",
        "Pointer whirlpool",
        "Equity wave reservoir",
        "Liquid glass market lens",
    ],
    citadel: [
        "Capital skybridges",
        "Changing-pair beacon shafts",
        "Architectural blueprint lock",
        "Capital skyline meter",
        "Architectural market blueprint",
    ],
    redline: [
        "Segmented velocity rails",
        "Quote afterburner streaks",
        "Steerable apex gate",
        "Profit rev counter",
        "Timing-board telemetry lock",
    ],
    synapse: [
        "Braided axon helices",
        "Changing-pair synaptic arcs",
        "Dendrite focus cage",
        "Branching profit cortex",
        "Neural market synapse",
    ],
    spectrum: [
        "Prismatic ribbons",
        "Quote dispersion fans",
        "Kaleidoscope lens",
        "Refracted profit fan",
        "Prismatic market loupe",
    ],
    horizon: [
        "Gravitational photon arcs",
        "Quote accretion streams",
        "Lensing caustic rings",
        "P&L convergence well",
        "Gravitational market focus",
    ],
    overdrive: [
        "Layered circuit raceways",
        "Quote packet launch columns",
        "Command crosshair matrix",
        "Profit packet matrix",
        "Market terminal hotlink",
    ],
};
